### ISSUE TITLE
Request for package release on PyPi

### ISSUE THREAD

**Issue by maurapintor** [jeromerony/adversarial-library#10]
Hi @jeromerony!

We would like to include this library as an extra dependency in [SecML-Torch](https://github.com/pralab/secml-torch). 
However, using `adv_lib` prevents us from publishing the package in PyPi, as published packages cannot depend on packages which are not also hosted on PyPI. 

Is there a chance that the library will be published as a package on PyPi at some point? I don't think that there are other workarounds for us here (except dropping the extra completely).

Thanks for your support!

**Comment by jeromerony** [comment]
Hi,

I had no plan on releasing the package on PyPi, mostly because this library was always aimed at researchers. Not everything needs to be distributed as a package, and especially not research code IMHO.

With that being said, I can look into and if it's not too much trouble, that can be done. I'll keep you posted.

**Comment by jeromerony** [comment]
Package is now available on PyPi: https://pypi.org/project/adv-lib/
Let me know if it works as intended.

**Comment by maurapintor** [comment]
Thank you @jeromerony! It works as intended.
